name: Check Pull Request

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  Check-Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - name: linux
          file: samory
    steps:
      - uses: actions/checkout@v3
        with:
           lfs: true
      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: ${{ matrix.platform.file }}
          preset: ${{ matrix.platform.name }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Samory - ${{ matrix.platform.name }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
