name: Check Pull Request

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  Check-Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows]
    steps:
      - uses: actions/checkout@v3
        with:
           lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: samory
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }
